### ISSUE TITLE
Change how the meme generating works

### ISSUE THREAD

**Issue by cameronsamuels** [cameronsamuels/memerator#55]
We will still need to have the canvas, but what we could have an `img` tag too. This will make the canvas invisible and remove the need for the `background-image` for the canvas. This will also let the image be available to right click and have more options than just save and inspect (on mobile it is none). This will allow the image to be right clicked and clicking save image, open image, copy address, copy image, and more. This will also allow the image to only have the final meme without seeing all the edits one at a time with the canvas being there.

@Pipe-to-Grep, please comment to approve this.

**Comment by Pipe-to-Grep** [comment]
I dont think we need to do this. However, i dont think it would be a bad idea to convert the canvas to img upon clicking a done button.

_Sent from my LGE LG-M430 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CameronSamuels** [comment]
@Pipe-to-Grep 

We can put this on hold and close it for now.

It is just sometimes the download button doesn't work because the image is too high so people can' download it. They need to right click. And on mobile, you can't hold down (definately on iOS) to save the canvas, only for `img`. So I think this is great to do.

**Comment by CameronSamuels** [comment]
This might be able to solve #63.
